### ISSUE TITLE
Some datasets cannot be called from the method chain

### ISSUE THREAD

**Issue by kojix2** [kojix2/rdatasets#4]
```ruby

Failures:

  1) RDatasets respond to the dataset name InfantMortality
     Failure/Error: expect(package_object.respond_to?(dataset)).to be true
     
       expected true
            got false
     # ./spec/rdatasets_spec.rb:61:in `block (4 levels) in <top (required)>'

  2) RDatasets can load the Stat2Data/InfantMortality dataset with method chain
     Failure/Error: super
     
     NoMethodError:
       undefined method `InfantMortality' for #<RDatasets::Package:0x0000562051317a50>
     # ./lib/rdatasets.rb:21:in `method_missing'
     # ./spec/rdatasets_spec.rb:77:in `public_send'
     # ./spec/rdatasets_spec.rb:77:in `block (4 levels) in <top (required)>'

  3) RDatasets respond to the dataset name LeafHoppers
     Failure/Error: expect(package_object.respond_to?(dataset)).to be true
     
       expected true
            got false
     # ./spec/rdatasets_spec.rb:61:in `block (4 levels) in <top (required)>'

  4) RDatasets can load the Stat2Data/LeafHoppers dataset with method chain
     Failure/Error: super
     
     NoMethodError:
       undefined method `LeafHoppers' for #<RDatasets::Package:0x0000562054a58e10>
     # ./lib/rdatasets.rb:21:in `method_missing'
     # ./spec/rdatasets_spec.rb:77:in `public_send'
     # ./spec/rdatasets_spec.rb:77:in `block (4 levels) in <top (required)>'

  5) RDatasets respond to the dataset name genfan
     Failure/Error: expect(package_object.respond_to?(dataset)).to be true
     
       expected true
            got false
     # ./spec/rdatasets_spec.rb:61:in `block (4 levels) in <top (required)>'

  6) RDatasets can load the survival/genfan dataset with method chain
     Failure/Error: super
     
     NoMethodError:
       undefined method `genfan' for #<RDatasets::Package:0x000056205513a580>
     # ./lib/rdatasets.rb:21:in `method_missing'
     # ./spec/rdatasets_spec.rb:77:in `public_send'
     # ./spec/rdatasets_spec.rb:77:in `block (4 levels) in <top (required)>'

Finished in 21 minutes 3 seconds (files took 19.67 seconds to load)
8127 examples, 6 failures

Failed examples:

rspec ./spec/rdatasets_spec.rb[1:2358] # RDatasets respond to the dataset name InfantMortality
rspec ./spec/rdatasets_spec.rb[1:2361] # RDatasets can load the Stat2Data/InfantMortality dataset with method chain
rspec ./spec/rdatasets_spec.rb[1:2390] # RDatasets respond to the dataset name LeafHoppers
rspec ./spec/rdatasets_spec.rb[1:2393] # RDatasets can load the Stat2Data/LeafHoppers dataset with method chain
rspec ./spec/rdatasets_spec.rb[1:5198] # RDatasets respond to the dataset name genfan
rspec ./spec/rdatasets_spec.rb[1:5201] # RDatasets can load the survival/genfan dataset with method chain
```

**Comment by kojix2** [comment]
Reported to upstream...

**Comment by kojix2** [comment]
New upstream release. Solved.
